version: '3'
services:
  golang-api:
    image: golang
    volumes:
      - .:/go/src
    command: /bin/bash -c "cd src && go run *.go"
    ports:
    - 8080:8080
    - 5000:5000
    depends_on:
    - mongo
    - rabbitmq
  mongo:
    image: mongo
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI