version: '3'
services:
  golang-api:
    image: golang
    volumes:
      - .:/go/src
    command: /bin/bash -c "cd src && go run *.go"
    ports:
    - 8080:8080
    - 5000:5000
    depends_on:
    - mongo
  mongo:
    image: mongo
